In [85]:
#Importing required packages
import numpy as np      
import pandas as pd      
import os
import matplotlib.pyplot as plt #visualization
from PIL import  Image
%matplotlib inline
import seaborn as sns
import itertools
import warnings
warnings.filterwarnings("ignore")
import io
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.tools as tls

In [86]:
#Reading the dataset
data= pd.read_csv("train.csv")   
#and visualizing the data heads
data.head(5)

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,...,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,...,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,...,37.772004,-122.431619,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,https://a0.muscache.com/im/pictures/72208dad-9...,94117.0,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,...,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0

In [87]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74111 entries, 0 to 74110
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      74111 non-null  int64
 1   log_price               74111 non-null  float64
 2   property_type           74111 non-null  object
 3   room_type               74111 non-null  object
 4   amenities               74111 non-null  object
 5   accommodates            74111 non-null  int64
 6   bathrooms               73911 non-null  float64
 7   bed_type                74111 non-null  object
 8   cancellation_policy     74111 non-null  object
 9   cleaning_fee            74111 non-null  bool
 10  city                    74111 non-null  object
 11  description             74111 non-null  object
 12  first_review            58247 non-null  object
 13  host_has_profile_pic    73923 non-null  object
 14  host_identity_verified  73923 non-null  object
 15  host_response_rate      55812 non-null  object
 16  host_since              73923 non-null  object
 17  instant_bookable        74111 non-null  object
 18  last_review             58284 non-null  object
 19  latitude                74111 non-null  float64
 20  longitude               74111 non-null  float64
 21  name                    74111 non-null  object
 22  neighbourhood           67239 non-null  object
 23  number_of_reviews       74111 non-null  int64
 24  review_scores_rating    57389 non-null  float64
 25  thumbnail_url           65895 non-null  object
 26  zipcode                 73145 non-null  object
 27  bedrooms                74020 non-null  float64
 28  beds                    73980 non-null  float64
dtypes: bool(1), float64(7), int64(3), object(18)
memory usage: 15.9+ MB

In [88]:
data.duplicated().sum()#Duplicating the dataset

0

In [89]:
data.isnull().sum()

id                            0
log_price                     0
property_type                 0
room_type                     0
amenities                     0
accommodates                  0
bathrooms                   200
bed_type                      0
cancellation_policy           0
cleaning_fee                  0
city                          0
description                   0
first_review              15864
host_has_profile_pic        188
host_identity_verified      188
host_response_rate        18299
host_since                  188
instant_bookable              0
last_review               15827
latitude                      0
longitude                     0
name                          0
neighbourhood              6872
number_of_reviews             0
review_scores_rating      16722
thumbnail_url              8216
zipcode                     966
bedrooms                     91
beds                        131
dtype: int64

In [90]:
data.describe()

,id,log_price,accommodates,bathrooms,latitude,longitude,number_of_reviews,review_scores_rating,bedrooms,beds
count,7.411100e+04,74111.000000,74111.000000,73911.000000,74111.000000,74111.000000,74111.000000,57389.000000,74020.000000,73980.000000
mean,1.126662e+07,4.782069,3.155146,1.235263,38.445958,-92.397525,20.900568,94.067365,1.265793,1.710868
std,6.081735e+06,0.717394,2.153589,0.582044,3.080167,21.705322,37.828641,7.836556,0.852143,1.254142
min,3.440000e+02,0.000000,1.000000,0.000000,33.338905,-122.511500,0.000000,20.000000,0.000000,0.000000
25%,6.261964e+06,4.317488,2.000000,1.000000,34.127908,-118.342374,1.000000,92.000000,1.000000,1.000000
50%,1.225415e+07,4.709530,2.000000,1.000000,40.662138,-76.996965,6.000000,96.000000,1.000000,1.000000
75%,1.640226e+07,5.220356,4.000000,1.000000,40.746096,-73.954660,23.000000,100.000000,1.000000,2.000000
max,2.123090e+07,7.600402,16.000000,8.000000,42.390437,-70.985047,605.000000,100.000000,10.000000,18.000000

In [91]:
data_boolean = data[["instant_bookable", "host_identity_verified", "host_has_profile_pic", "cleaning_fee"]]
#converting the bool feature tothe string
data_boolean['cleaning_fee'] = data_boolean['cleaning_fee'].map({True: 't', False: 'f'})

# Handling Missing Data

Case 1. Some columns are not needed for the operation, So they'll be easily dropped.

Case 2. There are a few options for filling in missing values in columns with numeric values, and I chose mean permutation.

Case 3. There's an exception for 'host response rate', which requires converting Percentage to decimal before permuting the mean.

Case 4. Missing values will be replaced with False in the case of Booleans.

In [92]:
#Case 1:
data.drop(['id','description','first_review','last_review','host_since','host_has_profile_pic','name','thumbnail_url','zipcode','neighbourhood'], axis=1, inplace=True)

In [93]:
#Case 2:
data['bathrooms'].fillna(data['bathrooms'].mean(), inplace=True)
data['review_scores_rating'].fillna(data['review_scores_rating'].mean(), inplace=True)
data['bedrooms'].fillna(data['bedrooms'].mean(), inplace=True)
data['beds'].fillna(data['beds'].mean(), inplace=True)

#Case 3:
data['host_response_rate'] = data['host_response_rate'].str[:-1].astype('float') / 100.0
data['host_response_rate'].fillna(data['host_response_rate'].mean(), inplace=True)

#Case 4:
data['host_identity_verified'] = data['host_identity_verified'].fillna(method='ffill')

In [94]:
category_var = data.select_dtypes(include = 'object')
num_var = data.select_dtypes(exclude = 'object')

print("Number of categorical features are: ", category_var.shape[1])
print("Number of numerical features are: ", num_var.shape[1])

Number of categorical features are:  8
Number of numerical features are:  11

In [95]:
#Label encoding across multiple columns in scikit-learn
#https://stackoverflow.com/questions/24458645/label-encoding-across-multiple-columns-in-scikit-learn

from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline


class MultiColumnLabelEncoder:
    def __init__(self,columns = None):
        self.columns = columns # array of column names to encode

    def fit(self,X,y=None):
        return self # not relevant here

    def transform(self,X):
        '''
        Transforms columns of X specified in self.columns using
        LabelEncoder(). If no columns specified, transforms all
        columns in X.
        '''
        output = X.copy()
        if self.columns is not None:
            for col in self.columns:
                output[col] = LabelEncoder().fit_transform(output[col])
        else:
            for colname,col in output.iteritems():
                output[colname] = LabelEncoder().fit_transform(col)
        return output

    def fit_transform(self,X,y=None):
        return self.fit(X,y).transform(X)

In [96]:
data_encoded = MultiColumnLabelEncoder(columns = ['room_type','amenities','host_identity_verified','cancellation_policy','property_type','bed_type','instant_bookable','city','cleaning_fee']).fit_transform(data)

In [97]:
data_encoded

,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,host_identity_verified,host_response_rate,instant_bookable,latitude,longitude,number_of_reviews,review_scores_rating,bedrooms,beds
0,5.010635,0,0,6142,3,1.0,4,2,1,4,1,0.94352,0,40.696524,-73.991617,2,100.000000,1.0,1.0
1,5.129899,0,0,6269,7,1.0,4,2,1,4,0,1.00000,1,40.766115,-73.989040,6,93.000000,3.0,3.0
2,4.976734,0,0,21345,5,1.0,4,1,1,4,1,1.00000,1,40.808110,-73.943756,10,92.000000,1.0,3.0
3,6.620073,17,0,38854,4,1.0,4,0,1,5,1,0.94352,0,37.772004,-122.431619,0,94.067365,2.0,2.0
4,4.744932,0,0,55413,2,1.0,4,1,1,2,1,1.00000,1,38.925627,-77.034596,4,40.000000,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74106,4.605170,0,1,67121,1,1.0,4,0,0,4,1,0.94352,0,40.709025,-73.939405,0,94.067365,1.0,1.0
74107,5.043425,0,0,38652,4,2.0,4,1,1,3,0,1.00000,0,33.871549,-118.396053,16,93.000000,2.0,4.0
74108,5.220356,0,0,61276,5,1.0,4,1,1,4,1,1.00000,1,40.706749,-73.942377,43,94.000000,2.0,2.0
74109,5.273000,0,0,48796,2,1.0,4,2,1,4,0,1.00000,1,40.738535,-74.000157,0,94.067365,0.0,2.0
74110,4.852030,2,0,65022,4,1.0,4,1,0,3,1,1.00000,0,33.761096,-118.192409,205,96.000000,1.0,2.0

In [98]:
## load dependencies
import smogn

In [99]:
## specify phi relevance values
rg_mtrx = [

    [35000,  1, 0],  ## over-sample ("minority")
    [125000, 0, 0],  ## under-sample ("majority")
    [200000, 0, 0],  ## under-sample
    [250000, 0, 0],  ## under-sample
]

In [100]:
%%time
## conduct smogn
housing_smogn = smogn.smoter(
    
    ## main arguments
    data = data_encoded,           ## pandas dataframe
    y = 'log_price',          ## string ('header name')
    k = 7,                    ## positive integer (k < n)
    pert = 0.5,              ## real number (0 < R < 1)
    samp_method = 'balance',  ## string ('balance' or 'extreme')
    drop_na_col = True,       ## boolean (True or False)
    drop_na_row = True,       ## boolean (True or False)
    replace = False,          ## boolean (True or False)

    ## phi relevance arguments
    rel_thres = 0.50,         ## real number (0 < R < 1)
    rel_method = 'auto',    ## string ('auto' or 'manual')
    rel_xtrm_type = 'both', ## unused (rel_method = 'manual')
    rel_coef = 1.50,        ## unused (rel_method = 'manual')
    rel_ctrl_pts_rg = rg_mtrx ## 2d array (format: [x, y])
)

dist_matrix:   1%|          | 39/5738 [01:56<4:44:05,  2.99s/it]

KeyboardInterrupt:

In [102]:
housing_smogn

,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,host_identity_verified,host_response_rate,instant_bookable,latitude,longitude,number_of_reviews,review_scores_rating,bedrooms,beds
0,5.914426,7,0,22419,5,2.395862,4,2,0,3,0,0.848966,0,34.682217,-119.557453,11,96.979310,2.395862,4.489655
1,5.672676,17,0,17590,5,1.833617,4,0,1,4,1,0.907241,0,37.084250,-121.784503,1,100.000000,1.833617,2.667235
2,5.896856,25,0,42092,8,2.500000,4,0,0,3,0,0.872051,0,34.051832,-118.439580,0,94.067365,4.000000,4.508170
3,6.094038,0,0,67121,2,1.158344,4,0,0,5,1,0.943520,0,37.735484,-122.453855,0,94.067365,0.673052,1.478451
4,5.996048,4,0,49980,9,2.269565,4,2,1,4,0,0.984775,0,36.715519,-121.387703,0,95.666595,2.539130,4.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18961,3.256902,17,2,6418,1,2.000000,4,2,1,3,0,1.000000,1,34.066109,-118.360412,1,95.531808,1.000000,1.000000
18962,3.595997,0,1,16739,1,1.000000,4,1,0,4,0,0.974771,0,40.754467,-73.949349,3,92.766547,1.000000,1.000000
18963,3.638161,11,1,10077,1,1.000000,4,0,1,4,0,1.000000,0,40.681730,-74.011361,57,80.559694,1.000000,1.000000
18964,3.415446,13,1,7831,1,1.000000,4,0,0,2,0,0.985108,0,39.400183,-76.224126,0,94.067365,1.000000,1.000000
18965,3.539202,0,1,52380,1,1.000000,4,0,0,4,1,0.943520,0,40.700957,-73.934284,0,94.067365,1.000000,1.000000

In [409]:
from sklearn.model_selection import train_test_split

X = housing_smogn.drop(['log_price'], axis = 1)
y = housing_smogn['log_price']

In [410]:
#Apply Square Root Scaling
y_sqrt = np.sqrt(y)

In [411]:
y=y_sqrt

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"There are {X_train.shape[0]} traning data")
print(f"There are {X_test.shape[0]} test data")

There are 67812 traning data
There are 16953 test data

In [412]:
from sklearn.preprocessing import StandardScaler

# define standard scaler
scaler = StandardScaler()
# transform data
X_trainScaled = scaler.fit_transform(X_train)
X_testScaled = scaler.transform(X_test)

# Machine Learning Models

Our goal is to forecast the price depending on the dataset provided. We must perform a regression task; because price is a continuous variable. As a result, we'll use regression models.

We're not looking for accuracy; because we're working on a regression problem rather than a classification one. Our primary metric will be mean squared error, which we will attempt to reduce; using techniques such as hyperparameter tuning.

# Linear Regression

Training the model

In [107]:
from sklearn.linear_model import LinearRegression

In [108]:
from sklearn.model_selection import GridSearchCV


params = {"fit_intercept": [True, False],
                 "n_jobs": [-1, 1, 2],
                 "copy_X": [True, False],
              "normalize": [True, False],
               "positive": [True, False]
             }
gs_LR = GridSearchCV(estimator=LinearRegression(),
                      param_grid=params,
                      cv=5)
gs_LR.fit(X_trainScaled, y_train)
gs_LR.best_params_

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': -1,
 'normalize': True,
 'positive': False}

In [109]:
# Create a Linear regressor with best parameters
lr = LinearRegression(copy_X= True,fit_intercept= True,n_jobs= -1,normalize= True,positive= False)

# Train the model using the training sets 
lr.fit(X_trainScaled, y_train)

LinearRegression(n_jobs=-1, normalize=True)

In [110]:
# Value of y intercept
lr.intercept_

2.1918373166198615

In [111]:
#Converting the coefficient values to a dataframe
coeffcients = pd.DataFrame([X_train.columns,lr.coef_]).T
coeffcients = coeffcients.rename(columns={0: 'Attribute', 1: 'Coefficients'})
coeffcients

            Attribute Coefficients
0       property_type     0.001016
1           room_type    -0.125626
2           amenities     0.009863
3        accommodates     0.057636
4           bathrooms     0.025061
5            bed_type     0.002375
6                city     0.016768
7            latitude     0.030476
8           longitude    -0.020717
9   number_of_reviews    -0.011267
10           bedrooms     0.036812
11               beds    -0.022092

In [112]:
# Model prediction on train data
y_pred = lr.predict(X_trainScaled)

In [113]:
# Model Evaluation
from sklearn import metrics
r2_lr_train = metrics.r2_score(y_train, y_pred)
adjust_lr_train = 1 - (1-metrics.r2_score(y_train, y_pred))*(len(y_train)-1)/(len(y_train)-X_trainScaled.shape[1]-1)
mae_lr_train = metrics.mean_absolute_error(y_train, y_pred)
mse_lr_train = metrics.mean_squared_error(y_train, y_pred)
rmse_lr_train = np.sqrt(metrics.mean_squared_error(y_train, y_pred))
models = pd.DataFrame({
    'Model': ['Linear Regression'],
    'R-squared Score Train': [r2_lr_train],
    'Adjusted R_squared Train': [adjust_lr_train],
    'MAE Train' : [mae_lr_train],
    'MSE Train': [mse_lr_train],
    'RMSE Train': [rmse_lr_train]
})
models

,Model,R-squared Score Train,Adjusted R_squared Train,MAE Train,MSE Train,RMSE Train
0,Linear Regression,0.604116,0.604046,0.116256,0.023701,0.153951

For test data

In [116]:
# Predicting Test data with the model
y_test_pred = lr.predict(X_testScaled)

In [117]:
# Model Evaluation
from sklearn import metrics
r2_lr_test = metrics.r2_score(y_test, y_test_pred)
adjust_lr_test = 1 - (1-metrics.r2_score(y_test, y_test_pred))*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)
mae_lr_test = metrics.mean_absolute_error(y_test, y_test_pred)
mse_lr_test = metrics.mean_squared_error(y_test, y_test_pred)
rmse_lr_test = np.sqrt(metrics.mean_squared_error(y_test, y_test_pred))
models = pd.DataFrame({
    'Model': ['Linear Regression'],
    'R-squared Score Test': [r2_lr_test],
    'Adjusted R_squared Test': [adjust_lr_test],
    'MAE Test' : [mae_lr_test],
    'MSE Test': [mse_lr_test],
    'RMSE Test': [rmse_lr_test]
})
models

,Model,R-squared Score Test,Adjusted R_squared Test,MAE Test,MSE Test,RMSE Test
0,Linear Regression,0.600664,0.600381,0.116747,0.023716,0.153999

# Decision Tree Regressor

In [118]:
from sklearn.tree import DecisionTreeRegressor

In [119]:
from sklearn.model_selection import GridSearchCV
params = {"max_depth": [5,10,15,20,25],
       'min_samples_split': [5,67,8,9],
         'min_samples_leaf': [35,40,45,50,55]
         }
gs_DT = GridSearchCV(estimator=DecisionTreeRegressor(),
                      param_grid=params,
                      cv=3)
gs_DT.fit(X_trainScaled, y_train)
gs_DT.best_params_

{'max_depth': 15, 'min_samples_leaf': 45, 'min_samples_split': 8}

In [131]:
# Create a DecisionTree regressor with best parameters
DT = DecisionTreeRegressor(max_depth= 15,min_samples_leaf= 45, min_samples_split=8)

# Train the model using the training sets 
DT.fit(X_trainScaled, y_train)

DecisionTreeRegressor(max_depth=15, min_samples_leaf=45, min_samples_split=8)

In [132]:
# Model prediction on train data
y_pred = DT.predict(X_trainScaled)

In [133]:
# Model Evaluation
from sklearn import metrics
r2_dt_train = metrics.r2_score(y_train, y_pred)
adjust_dt_train = 1 - (1-metrics.r2_score(y_train, y_pred))*(len(y_train)-1)/(len(y_train)-X_train.shape[1]-1)
mae_dt_train = metrics.mean_absolute_error(y_train, y_pred)
mse_dt_train = metrics.mean_squared_error(y_train, y_pred)
rmse_dt_train = np.sqrt(metrics.mean_squared_error(y_train, y_pred))
models = pd.DataFrame({
    'Model': ['Decision Tree Regressor'],
    'R-squared Score Train': [r2_dt_train],
    'Adjusted R_squared Train': [adjust_dt_train],
    'MAE Train' : [mae_dt_train],
    'MSE Train': [mse_dt_train],
    'RMSE Train': [rmse_dt_train]
})
models

,Model,R-squared Score Train,Adjusted R_squared Train,MAE Train,MSE Train,RMSE Train
0,Decision Tree Regressor,0.749316,0.749272,0.082124,0.015008,0.122507

For test data

In [134]:
# Predicting Test data with the model
y_test_pred = DT.predict(X_testScaled)

In [135]:
# Model Evaluation
from sklearn import metrics
r2_dt_test = metrics.r2_score(y_test, y_test_pred)
adjust_dt_test = 1 - (1-metrics.r2_score(y_test, y_test_pred))*(len(y_test)-1)/(len(y_test)-X_testScaled.shape[1]-1)
mae_dt_test = metrics.mean_absolute_error(y_test, y_test_pred)
mse_dt_test = metrics.mean_squared_error(y_test, y_test_pred)
rmse_dt_test = np.sqrt(metrics.mean_squared_error(y_test, y_test_pred))
models = pd.DataFrame({
    'Model': ['Decision Tree'],
    'R-squared Score Test': [r2_dt_test],
    'Adjusted R_squared Test': [adjust_dt_test],
    'MAE Test' : [mae_dt_test],
    'MSE Test': [mse_dt_test],
    'RMSE Test': [rmse_dt_test]
})
models

,Model,R-squared Score Test,Adjusted R_squared Test,MAE Test,MSE Test,RMSE Test
0,Decision Tree,0.717834,0.717634,0.087025,0.016757,0.12945

# Random Forest Regressor

In [136]:
from sklearn.ensemble import RandomForestRegressor
RandomForestRegressor().get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [140]:
from sklearn.model_selection import GridSearchCV

params = {
    'n_estimators':[500,600,700,800],
        'max_depth': [10,15,20],
     'max_features': [0.2,0.3,0.4],
    'min_samples_leaf':[11,12]
}
gs_RF = GridSearchCV(estimator=RandomForestRegressor(),
                      param_grid=params,
                      cv=3)
gs_RF.fit(X_trainScaled, y_train)
gs_RF.best_params_

{'max_depth': 0.3,
 'max_features': 0.3,
 'min_samples_leaf': 11,
 'n_estimators': 600}

In [235]:
# Create a Random Forest Regressor
RF = RandomForestRegressor(max_depth= 15, max_samples=0.4, n_estimators= 800, max_features= 0.7, min_samples_leaf=6)

# Train the model using the training sets 
RF.fit(X_trainScaled, y_train)

RandomForestRegressor(max_depth=15, max_features=0.7, max_samples=0.4,
                      min_samples_leaf=6, n_estimators=800)

In [236]:
# Model prediction on train data
y_pred = RF.predict(X_trainScaled)

In [237]:
# Model Evaluation
from sklearn import metrics
r2_rf_train = metrics.r2_score(y_train, y_pred)
adjust_rf_train = 1 - (1-metrics.r2_score(y_train, y_pred))*(len(y_train)-1)/(len(y_train)-X_trainScaled.shape[1]-1)
mae_rf_train = metrics.mean_absolute_error(y_train, y_pred)
mse_rf_train = metrics.mean_squared_error(y_train, y_pred)
rmse_rf_train = np.sqrt(metrics.mean_squared_error(y_train, y_pred))
models = pd.DataFrame({
    'Model': ['Random Forest Regressor'],
    'R-squared Score Train': [r2_rf_train],
    'Adjusted R_squared Train': [adjust_rf_train],
    'MAE Train' : [mae_rf_train],
    'MSE Train': [mse_rf_train],
    'RMSE Train': [rmse_rf_train]
})
models

,Model,R-squared Score Train,Adjusted R_squared Train,MAE Train,MSE Train,RMSE Train
0,Random Forest Regressor,0.791959,0.791917,0.072851,0.012483,0.111727

For test data

In [238]:
# Model prediction on train data
y_test_pred = RF.predict(X_testScaled)

In [239]:
# Model Evaluation
from sklearn import metrics
r2_rf_test = metrics.r2_score(y_test, y_test_pred)
adjust_rf_test = 1 - (1-metrics.r2_score(y_test, y_test_pred))*(len(y_test)-1)/(len(y_test)-X_testScaled.shape[1]-1)
mae_rf_test = metrics.mean_absolute_error(y_test, y_test_pred)
mse_rf_test = metrics.mean_squared_error(y_test, y_test_pred)
rmse_rf_test = np.sqrt(metrics.mean_squared_error(y_test, y_test_pred))
models = pd.DataFrame({
    'Model': ['Random Forest'],
    'R-squared Score Test': [r2_rf_test],
    'Adjusted R_squared Test': [adjust_rf_test],
    'MAE Test' : [mae_rf_test],
    'MSE Test': [mse_rf_test],
    'RMSE Test': [rmse_rf_test]
})
models

,Model,R-squared Score Test,Adjusted R_squared Test,MAE Test,MSE Test,RMSE Test
0,Random Forest,0.749055,0.748936,0.080296,0.014864,0.121919

# XGBoost Regressor

In [241]:
from xgboost import XGBRegressor

In [242]:
from sklearn.model_selection import GridSearchCV
params = {
       'learning_rate': [0.1,0.3,0.5], #so called `eta` value
           'max_depth': [7,8,9]
             }

gs_XGB = GridSearchCV(estimator=XGBRegressor(),
                      param_grid=params,
                      cv=3)
gs_XGB.fit(X_trainScaled, y_train)
gs_XGB.best_params_

{'learning_rate': 0.1, 'max_depth': 9}

In [341]:
# Create a XGB Regressor
xgbRegressor = XGBRegressor(n_estimators= 500, learning_rate= 0.1,max_depth= 5, min_child_weight=1, gamma=0.1, colsample_bytree=0.9)

# Train the model using the training sets 
xgbRegressor.fit(X_trainScaled, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=0.9,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0.1, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.1, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=5, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=500, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, ...)

In [342]:
# Model prediction on train data
y_pred = xgbRegressor.predict(X_trainScaled)

In [343]:
# Model Evaluation
from sklearn import metrics
r2_xgb_train = metrics.r2_score(y_train, y_pred)
adjust_xgb_train = 1 - (1-metrics.r2_score(y_train, y_pred))*(len(y_train)-1)/(len(y_train)-X_trainScaled.shape[1]-1)
mae_xgb_train = metrics.mean_absolute_error(y_train, y_pred)
mse_xgb_train = metrics.mean_squared_error(y_train, y_pred)
rmse_xgb_train = np.sqrt(metrics.mean_squared_error(y_train, y_pred))
models = pd.DataFrame({
    'Model': ['XGBoost'],
    'R-squared Score Train': [r2_xgb_train],
    'Adjusted R_squared Train': [adjust_xgb_train],
    'MAE Train' : [mae_xgb_train],
    'MSE Train': [mse_xgb_train],
    'RMSE Train': [rmse_xgb_train]
})
models

,Model,R-squared Score Train,Adjusted R_squared Train,MAE Train,MSE Train,RMSE Train
0,XGBoost,0.774669,0.774629,0.077579,0.01349,0.116148

For test data

In [344]:
#Predicting Test data with the model
y_test_pred = xgbRegressor.predict(X_testScaled)

In [345]:
# Model Evaluation
r2_xgb_test = metrics.r2_score(y_test, y_test_pred)
adjust_xgb_test = 1 - (1-metrics.r2_score(y_test, y_test_pred))*(len(y_test)-1)/(len(y_test)-X_testScaled.shape[1]-1)
mae_xgb_test = metrics.mean_absolute_error(y_test, y_test_pred)
mse_xgb_test = metrics.mean_squared_error(y_test, y_test_pred)
rmse_xgb_test = np.sqrt(metrics.mean_squared_error(y_test, y_test_pred))
models = pd.DataFrame({
    'Model': ['XGBoost'],
    'R-squared Score Test': [r2_xgb_test],
    'Adjusted R_squared Test': [adjust_xgb_test],
    'MAE Test' : [mae_xgb_test],
    'MSE Test': [mse_xgb_test],
    'RMSE Test': [rmse_xgb_test]
})
models

,Model,R-squared Score Test,Adjusted R_squared Test,MAE Test,MSE Test,RMSE Test
0,XGBoost,0.750086,0.749909,0.080734,0.014842,0.121827

# SVM Regressor

In [346]:
from sklearn import svm

In [347]:
from sklearn.model_selection import GridSearchCV
params = {
        'C': [0.1,1],
    'gamma': [0.1,1],
   'kernel': ['linear']
}
gs_SVM = GridSearchCV(estimator=svm.SVR(),
                      param_grid=params,
                      cv=3)
gs_SVM.fit(X_trainScaled, y_train)
gs_SVM.best_params_

{'C': 0.1, 'gamma': 0.1, 'kernel': 'linear'}

In [ ]:
# Create a suport Vector Machine Regressor
svmRegressor = svm.SVR(C= 25,gamma= 1e-3,kernel= 'linear')

# Train the model using the training sets 
svmRegressor.fit(X_trainScaled, y_train)

In [ ]:
# Model prediction on train data
y_pred = svmRegressor.predict(X_trainScaled)

In [ ]:
# Model Evaluation
from sklearn import metrics
r2_svm_train = metrics.r2_score(y_train, y_pred)
adjust_svm_train = 1 - (1-metrics.r2_score(y_train, y_pred))*(len(y_train)-1)/(len(y_train)-X_train.shape[1]-1)
mae_svm_train = metrics.mean_absolute_error(y_train, y_pred)
mse_svm_train = metrics.mean_squared_error(y_train, y_pred)
rmse_svm_train = np.sqrt(metrics.mean_squared_error(y_train, y_pred))
models = pd.DataFrame({
    'Model': ['SVM'],
    'R-squared Score Train': [r2_svm_train],
    'Adjusted R_squared Train': [adjust_svm_train],
    'MAE Train' : [mae_svm_train],
    'MSE Train': [mse_svm_train],
    'RMSE Train': [rmse_svm_train]
})
models

In [ ]:
# Predicting Test data with the model
y_test_pred = svmRegressor.predict(X_testScaled)

In [ ]:
# Model Evaluation
r2_svm_test = metrics.r2_score(y_test, y_test_pred)
adjust_svm_test = 1 - (1-metrics.r2_score(y_test, y_test_pred))*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)
mae_svm_test = metrics.mean_absolute_error(y_test, y_test_pred)
mse_svm_test = metrics.mean_squared_error(y_test, y_test_pred)
rmse_svm_test = np.sqrt(metrics.mean_squared_error(y_test, y_test_pred))
models = pd.DataFrame({
    'Model': ['SVM'],
    'R-squared Score Test': [r2_svm_test],
    'Adjusted R_squared Test': [adjust_svm_test],
    'MAE Test' : [mae_svm_test],
    'MSE Test': [mse_svm_test],
    'RMSE Test': [rmse_svm_test]
})
models

# Neural Network

In [358]:
import keras
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
from sklearn.model_selection import GridSearchCV 
from tensorflow.keras.wrappers.scikit_learn import KerasRegressor

In [403]:
from tensorflow.keras.optimizers import SGD
nnRegressor = Sequential()

# Adding the input layer and the first hidden layer
nnRegressor.add(Dense(128, activation = 'relu', input_dim=X_train.shape[1]))

# Adding the second hidden layer
nnRegressor.add(Dense(64, activation = 'relu'))

nnRegressor.add(Dense(32, activation = 'relu'))

nnRegressor.add(Dense(8, activation = 'relu'))

# Adding the output layer
nnRegressor.add(Dense(1, activation='linear'))
opt=SGD(lr=0.1)
# Compiling the model
nnRegressor.compile(loss='mean_squared_error', optimizer=opt)

# Fitting the ANN to the Training set
nnRegressor.fit(X_trainScaled, y_train ,batch_size = 50, epochs = 100, verbose=1)

Epoch 1/100
1357/1357 [==============================] - 7s 4ms/step - loss: 0.0323
Epoch 2/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0205
Epoch 3/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0201
Epoch 4/100
1357/1357 [==============================] - 6s 4ms/step - loss: 0.0198
Epoch 5/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0197
Epoch 6/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0195
Epoch 7/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0194
Epoch 8/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0192
Epoch 9/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0192
Epoch 10/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0191
Epoch 11/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0190
Epoch 12/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0189
Epoch 13/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0189
Epoch 14/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0188
Epoch 15/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0187
Epoch 16/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0187
Epoch 17/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0186
Epoch 18/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0186
Epoch 19/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0185
Epoch 20/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0185
Epoch 21/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0184
Epoch 22/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0184
Epoch 23/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0184
Epoch 24/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0183
Epoch 25/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0183
Epoch 26/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0182
Epoch 27/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0182
Epoch 28/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0182
Epoch 29/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0182
Epoch 30/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0181
Epoch 31/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0181
Epoch 32/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0180
Epoch 33/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0180
Epoch 34/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0180
Epoch 35/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0179
Epoch 36/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0179
Epoch 37/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0179
Epoch 38/100
1357/1357 [==============================] - 6s 4ms/step - loss: 0.0179
Epoch 39/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0178
Epoch 40/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0179
Epoch 41/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0178
Epoch 42/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0177
Epoch 43/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0178
Epoch 44/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0177
Epoch 45/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0177
Epoch 46/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0176
Epoch 47/100
1357/1357 [==============================] - 6s 4ms/step - loss: 0.0176
Epoch 48/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0176
Epoch 49/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0176
Epoch 50/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0176
Epoch 51/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0176
Epoch 52/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0175
Epoch 53/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0175
Epoch 54/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0175
Epoch 55/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0174
Epoch 56/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0174
Epoch 57/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0174
Epoch 58/100
1357/1357 [==============================] - 6s 4ms/step - loss: 0.0174
Epoch 59/100
1357/1357 [==============================] - 6s 4ms/step - loss: 0.0174
Epoch 60/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0174
Epoch 61/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0174
Epoch 62/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0174
Epoch 63/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0173
Epoch 64/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0173
Epoch 65/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0173
Epoch 66/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0173
Epoch 67/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0173
Epoch 68/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0172
Epoch 69/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0172
Epoch 70/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0172
Epoch 71/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0172
Epoch 72/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0172
Epoch 73/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0171
Epoch 74/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0171
Epoch 75/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0171
Epoch 76/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0171
Epoch 77/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0171
Epoch 78/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0171
Epoch 79/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0171
Epoch 80/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0170
Epoch 81/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0170
Epoch 82/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0170
Epoch 83/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0170
Epoch 84/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0170
Epoch 85/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0170
Epoch 86/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0169
Epoch 87/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0170
Epoch 88/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0169
Epoch 89/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0169
Epoch 90/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0169
Epoch 91/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0169
Epoch 92/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0169
Epoch 93/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0169
Epoch 94/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0168
Epoch 95/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0168
Epoch 96/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0168
Epoch 97/100

1357/1357 [==============================] - 5s 4ms/step - loss: 0.0168
Epoch 98/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0168
Epoch 99/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0168
Epoch 100/100
1357/1357 [==============================] - 5s 4ms/step - loss: 0.0168

In [404]:
#Model prediction on train data
y_pred = nnRegressor.predict(X_trainScaled)

2120/2120 [==============================] - 6s 3ms/step

In [405]:
from sklearn import metrics
r2_nn_train = metrics.r2_score(y_train, y_pred)
adjust_nn_train = 1 - (1-metrics.r2_score(y_train, y_pred))*(len(y_train)-1)/(len(y_train)-X_trainScaled.shape[1]-1)
mae_nn_train = metrics.mean_absolute_error(y_train, y_pred)
mse_nn_train = metrics.mean_squared_error(y_train, y_pred)
rmse_nn_train = np.sqrt(metrics.mean_squared_error(y_train, y_pred))
print('R^2:', r2_nn_train)
print('Adjusted R^2:', adjust_nn_train)
print('MAE:', mae_nn_train)
print('MSE:', mse_nn_train)
print('RMSE:', rmse_nn_train)

R^2: 0.7245239739109419
Adjusted R^2: 0.7244752163730274
MAE: 0.08968442917789589
MSE: 0.016492335711487394
RMSE: 0.12842248911887433

In [406]:
# Predicting Test data with the model
y_test_pred = nnRegressor.predict(X_testScaled)

530/530 [==============================] - 2s 3ms/step

In [407]:
# Model Evaluation
r2_nn_test = metrics.r2_score(y_test, y_test_pred)
adjust_nn_test = 1 - (1-metrics.r2_score(y_test, y_test_pred))*(len(y_test)-1)/(len(y_test)-X_testScaled.shape[1]-1)
mae_nn_test = metrics.mean_absolute_error(y_test, y_test_pred)
mse_nn_test = metrics.mean_squared_error(y_test, y_test_pred)
rmse_nn_test = np.sqrt(metrics.mean_squared_error(y_test, y_test_pred))
print('R^2:', r2_nn_test)
print('Adjusted R^2:', adjust_nn_test)
print('MAE:', mae_nn_test)
print('MSE:', mse_nn_test)
print('RMSE:', rmse_nn_test)

R^2: 0.6955324592323011
Adjusted R^2: 0.6953167797465152
MAE: 0.09340089003605098
MSE: 0.018081744881899956
RMSE: 0.1344683787434799

6 different Models were trained and R^2 scores are obtained, Now it comes to comparision.

# Conclusion

In [408]:
models = pd.DataFrame({
    'Model': ['Linear Regression', 'Decision Tree','Random Forest', 'SVM', 'XGBoost','Neural Networks'],
    'R-squared Score Train': [r2_lr_train, r2_dt_train, r2_rf_train, r2_svm_train, r2_xgb_train, r2_nn_train],
    'R-squared Score Test': [r2_lr_test, r2_dt_test, r2_rf_test, r2_svm_test, r2_xgb_test, r2_nn_test],
    'Adjusted R_squared Train': [adjust_lr_train, adjust_dt_train, adjust_rf_train, adjust_svm_train, adjust_xgb_train, adjust_nn_train],
  'Adjusted R_squared Test': [adjust_lr_test, adjust_dt_test, adjust_rf_test, adjust_svm_test, adjust_xgb_test, adjust_nn_test],
    'MAE Train': [mae_lr_train, mae_dt_train, mae_rf_train, mae_svm_train, mae_xgb_train, mae_nn_train],
    'MAE Test': [mae_lr_test, mae_dt_test, mae_rf_test, mae_svm_test, mae_xgb_test, mae_nn_test],
    'MSE Train': [mse_lr_train, mse_dt_train, mse_rf_train, mse_svm_train, mse_xgb_train, mse_nn_train],
    'MSE Test': [mse_lr_test, mse_dt_test, mse_rf_test, mse_svm_test, mse_xgb_test, mse_nn_test],
    'RMSE Train': [rmse_lr_train, rmse_dt_train, rmse_rf_train, rmse_svm_train, rmse_xgb_train, rmse_nn_train],
    'RMSE Test': [rmse_lr_test, rmse_dt_test, rmse_rf_test, rmse_svm_test, rmse_xgb_test, rmse_nn_test]
})
models

,Model,R-squared Score Train,R-squared Score Test,Adjusted R_squared Train,Adjusted R_squared Test,MAE Train,MAE Test,MSE Train,MSE Test,RMSE Train,RMSE Test
0,Linear Regression,0.604116,0.600664,0.604046,0.600381,0.116256,0.116747,0.023701,0.023716,0.153951,0.153999
1,Decision Tree,0.749316,0.717834,0.749272,0.717634,0.082124,0.087025,0.015008,0.016757,0.122507,0.129450
2,Random Forest,0.791959,0.749055,0.791917,0.748936,0.072851,0.080296,0.012483,0.014864,0.111727,0.121919
3,SVM,0.602283,0.598710,0.602213,0.598426,0.115556,0.116007,0.023811,0.023832,0.154307,0.154376
4,XGBoost,0.774669,0.750086,0.774629,0.749909,0.077579,0.080734,0.013490,0.014842,0.116148,0.121827
5,Neural Networks,0.724524,0.695532,0.724475,0.695317,0.089684,0.093401,0.016492,0.018082,0.128422,0.134468